// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.

// Example 1:

let s = "abcd";
let t = "abcde";

// Output: "e"
// Explanation: 'e' is the letter that was added.
// Example 2:

// let s = "";
// let t = "y";
// Output: "y"

// var findTheDifference = function (s, t) {
//   const s1 = s.split("").sort();
//   const t1 = t.split("").sort();

//   for (let i = 0; i < t1.length; i++) {
//     if (s1[i] !== t1[i]) {
//       return t1[i];
//     }
//   }
// };
// console.log(findTheDifference(s, t));

var findTheDifference = function (s, t) {
  const count = new Array(26).fill(0);

  for (let char of s) {
    count[char.charCodeAt(0) - "a".charCodeAt(0)]++;
  }

  for (let char of t) {
    count[char.charCodeAt(0) - "a".charCodeAt(0)]--;
  }

  for (let i = 0; i < 26; i++) {
    if (count[i] < 0) {
      return String.fromCharCode("a".charCodeAt(0) + i);
    }
  }

  return "";
};

console.log(findTheDifference(s, t));
